import { supabase } from "../supabase";
import type { Mission } from "../../types/entities";
import { sanitizeName } from "../../utils/sanitize";

/** Fields accepted when creating a mission (id and created_at are generated by the database). */
export type MissionInsert = Omit<Mission, "id" | "created_at"> & { user_id: string };

/** Fields accepted when updating a mission. */
export type MissionUpdate = Partial<Omit<Mission, "id" | "user_id" | "created_at">>;

export const fetchMissions = async (): Promise<Mission[]> => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];

  const { data: profileData } = await supabase
    .from("profiles")
    .select("role, patron_id")
    .eq("id", user.id)
    .single();

  const isViewer = profileData?.role === "viewer";
  const isPatron = profileData?.role === "patron";

  let query = supabase
    .from("missions")
    .select("*")
    .order("date_mission", { ascending: false, nullsFirst: false })
    .order("date_iso", { ascending: false });

  // Pour viewer et patron : pas de filtre user_id, RLS gère la sécurité
  if (!isViewer && !isPatron) {
    query = query.eq("user_id", user.id);
  }

  const { data, error } = await query;
  if (error) throw error;

  return (data || []) as Mission[];
};

export const createMission = async (missionData: Partial<Mission>): Promise<Mission> => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Utilisateur non connecté");

  const payload: MissionInsert = {
    ...(missionData as Omit<Mission, "id" | "created_at">),
    user_id: user.id,
    date_mission: missionData.date_mission || missionData.date_iso || null,
    ...(missionData.client != null && { client: sanitizeName(missionData.client) }),
    ...(missionData.lieu != null && { lieu: sanitizeName(missionData.lieu) }),
  };

  const { data, error } = await supabase
    .from("missions")
    .insert([payload])
    .select();

  if (error) {
    console.error("🔴 API - Erreur Supabase:", {
      message: error.message,
      details: error.details,
      hint: error.hint,
      code: error.code,
    });
    throw error;
  }

  return data[0] as Mission;
};

export const updateMission = async (id: string, missionData: Partial<Mission>): Promise<Mission> => {
  const payload: MissionUpdate = {
    ...(missionData as MissionUpdate),
    ...(missionData.client != null && { client: sanitizeName(missionData.client) }),
    ...(missionData.lieu != null && { lieu: sanitizeName(missionData.lieu) }),
  };
  if (missionData.date_iso) {
    payload.date_mission = missionData.date_iso;
  }

  const { data, error } = await supabase
    .from("missions")
    .update(payload)
    .eq("id", id)
    .select();

  if (error) {
    console.error("🔴 API - Erreur Supabase (update):", {
      message: error.message,
      details: error.details,
      hint: error.hint,
      code: error.code,
    });
    throw error;
  }

  return data[0] as Mission;
};

export const deleteMission = async (id: string): Promise<void> => {
  const { error } = await supabase.from("missions").delete().eq("id", id);
  if (error) throw error;
};

export const bulkInsertMissions = async (missionsArray: Partial<Mission>[]): Promise<Mission[]> => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Utilisateur non connecté");

  const payloads = missionsArray.map((m) => ({
    ...m,
    user_id: user.id,
    date_mission: m.date_iso,
    ...(m.client != null && { client: sanitizeName(m.client) }),
    ...(m.lieu != null && { lieu: sanitizeName(m.lieu) }),
  }));

  const { data, error } = await supabase
    .from("missions")
    .insert(payloads)
    .select();

  if (error) throw error;
  return (data || []) as Mission[];
};
