export const EUROPE_COUNTRIES = [
  { code: "AT", label: "Autriche" },
  { code: "BE", label: "Belgique" },
  { code: "BG", label: "Bulgarie" },
  { code: "CH", label: "Suisse" },
  { code: "CY", label: "Chypre" },
  { code: "CZ", label: "Tchéquie" },
  { code: "DE", label: "Allemagne" },
  { code: "DK", label: "Danemark" },
  { code: "EE", label: "Estonie" },
  { code: "ES", label: "Espagne" },
  { code: "FI", label: "Finlande" },
  { code: "FR", label: "France" },
  { code: "GB", label: "Royaume-Uni" },
  { code: "GR", label: "Grèce" },
  { code: "HR", label: "Croatie" },
  { code: "HU", label: "Hongrie" },
  { code: "IE", label: "Irlande" },
  { code: "IT", label: "Italie" },
  { code: "LT", label: "Lituanie" },
  { code: "LU", label: "Luxembourg" },
  { code: "LV", label: "Lettonie" },
  { code: "MT", label: "Malte" },
  { code: "NL", label: "Pays-Bas" },
  { code: "NO", label: "Norvège" },
  { code: "PL", label: "Pologne" },
  { code: "PT", label: "Portugal" },
  { code: "RO", label: "Roumanie" },
  { code: "SE", label: "Suède" },
  { code: "SI", label: "Slovénie" },
  { code: "SK", label: "Slovaquie" },
];

// Taux kilométriques recommandés par pays (€/km, véhicule léger)
export const KM_RATES = {
  AT: 0.42,
  BE: 0.42,
  BG: 0.20,
  CH: 0.70,
  CY: 0.25,
  CZ: 0.25,
  DE: 0.30,
  DK: 0.52,
  EE: 0.30,
  ES: 0.26,
  FI: 0.44,
  FR: 0.42,
  GB: 0.45,
  GR: 0.25,
  HR: 0.25,
  HU: 0.18,
  IE: 0.39,
  IT: 0.25,
  LT: 0.25,
  LU: 0.39,
  LV: 0.25,
  MT: 0.25,
  NL: 0.23,
  NO: 0.46,
  PL: 0.25,
  PT: 0.36,
  RO: 0.20,
  SE: 0.25,
  SI: 0.37,
  SK: 0.25,
};
